### ISSUE TITLE
error: failed to write /workspace/intro/hardware-check/Cargo.lock

### ISSUE THREAD

**Issue by linktel0** [esp-rs/std-training#202]
esp@3b9a22d3b7a6:/workspace/intro/hardware-check$ cargo run
    Updating crates.io index
error: failed to write /workspace/intro/hardware-check/Cargo.lock

Caused by:
  failed to open: /workspace/intro/hardware-check/Cargo.lock

Caused by:
  Permission denied (os error 13)

**Comment by SergioGasquez** [comment]
Hi! Would you mind giving more details? How are you trying to build the project? CI is building the example with the Docker image  with no issues

**Comment by SergioGasquez** [comment]
I will be closing the issue for inactivity, if the issue persists, feel free to reopen it
