### ISSUE TITLE
How can I implement a blinky code?

### ISSUE THREAD

**Issue by Song-aff** [esp-rs/std-training#206]
I can't find an example implemented using std.

**Comment by SergioGasquez** [comment]
> I can't find an example implemented using std.
> 
> 

In https://github.com/SergioGasquez/wokwi-projects#examples you can find Blinky examples in std for all chips. Also,on esp-idf-hal there are blinky examples for all the chips

**Comment by Song-aff** [comment]
https://github.com/esp-rs/esp-idf-hal/blob/master/examples/blinky.rs
thanks，and  I found this.
