### ISSUE TITLE
Building `esp-idf-sys` failed because of uninitialized submodules in esp-idf

### ISSUE THREAD

**Issue by rangerjo** [esp-rs/std-training#235]
Building `esp-idf-sys` failed because of uninitialized submodules in esp-idf.

Issuing `git submodle update --init --recursive` in the esp-idf directory at `~/.espressif/esp-idf/v5.1.2/` solved the issue.

However, when following the instructions in the std-training book, this is not mentioned, as this should all be handled under the hood. 

Just letting you know!

**Comment by Vollbrecht** [comment]
Usually that should not be needed. When the esp-idf's repo is pulled and github decided to have bad networking again, problems like this can arise. Still thanks that you mention a potential workaround, and give feedback ;) 

Happy Coding

**Comment by SergioGasquez** [comment]
`esp-idf-sys` should take care of downloading `esp-idf` with all the submodules. But sometimes, when not using a reliable network, the `esp-idf-sys` cloning of the `esp-idf` repo might fail, which looks like its what happened in your case

**Comment by rangerjo** [comment]
Ok, thank you for the responses, thats fine with me. Can be considered closed then!
