### ISSUE TITLE
esp32c2 uses 26M crystal oscillator, resulting in delay errors

### ISSUE THREAD

**Issue by xiaguangbo** [esp-rs/std-training#240]
I should configure the crystal frequency in "menuconfig" mode, but I don't know how to do this under "esp-rs"

**Comment by SergioGasquez** [comment]
If using a `std` project, which seems like you are since you opened this issue in `std-training`: https://docs.esp-rs.org/book/troubleshooting/espflash.html#if-you-are-building-an-esp-idf-sys-based-project

If using a `no_std` project, it should be automatically detected.

**Comment by xiaguangbo** [comment]
in sdkconfig.defaults add CONFIG_XTAL_FREQ_26=y，cargo clean cargo run is ok!
