### ISSUE TITLE
http-server example is not working with more recent ESP_IDF

### ISSUE THREAD

**Issue by dmk978** [esp-rs/std-training#268]
just replace ESP_IDF_VERSION with { value = "tag:v5.3.2" }

and example will always fail on:
let mut server = EspHttpServer::new(&Configuration::default())?;

**Comment by SergioGasquez** [comment]
I guess that is expected, the API may have changed between ESP-IDF versions. I would checking the API changes and try to adjust the code, in the future, we may want to update all the examples to a more recent ESP-IDF version, but thats not yet scheduled. 

Feel free to ask for some hints at the [matrix channel](https://matrix.to/#/#esp-rs:matrix.org)
