### ISSUE TITLE
Any documentation or examples on a xtensa hello world with std

### ISSUE THREAD

**Issue by SeaRoll** [esp-rs/std-training#269]
Hi!

Is there anyone here who has done with xtensa architecture for std?

Thanks!

**Comment by SergioGasquez** [comment]
Hi!

If you set your environment, as explained in https://docs.esp-rs.org/book/installation/index.html, updating the examples of this training should be "easy" (you may need to update the target set in `.cargo/config.toml` and so on). You could also generate a hello-world project using `esp-idf-template` as explained in https://docs.esp-rs.org/book/writing-your-own-application/generate-project/index.html
