### ISSUE TITLE
Can I translate the book into Chinese?

### ISSUE THREAD

**Issue by YuaXan** [esp-rs/std-training#76]
For title.

**Comment by Narukara** [comment]
I am translating now.

here: https://github.com/Narukara/espressif-trainings-cn

**Comment by SergioGasquez** [comment]
Hi! The book has received a major update, if the Chinese translation is up-to-date we could try to review it and include it officially if you are okay with that @Narukara.

I think it would be an awesome resource to have! Thanks for your efforts on translating!

**Comment by Narukara** [comment]
I'm okay with that. But the translation is not yet complete. This will take a little longer because I am currently busy with my graduation project.😢 I will be back in two months.

**Comment by SergioGasquez** [comment]
Of course, no worries. It should also give us time to curate it a bit more!

**Comment by SergioGasquez** [comment]
I just noticed that you resumed the translation @Narukara, thanks for all your efforts, do you think we can include it in this repo once its finished?

**Comment by SergioGasquez** [comment]
Hi! Again, thanks for all your efforts on translating! I see that your fork is updated (only missing the content a few minor commits) do you think we are ready to add that translations section and point to your book?

**Comment by Narukara** [comment]
Yes, I think we are ready. I'll probably finish the rest of my book within a few days.
